apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-external-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: shared-services
    server: {{ .Values.server }}
  project: shared-services
  source:
    path: helm_charts/kubernetes-external-secrets
    repoURL: git@github.com:TechTalkFridays/eks-shared-services.git
    targetRevision: production
    helm:
      valueFiles:
      - helm_vars/production/values.yaml
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
