apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: {{ .Release.Namespace }}
  labels:
    app: cluster-autoscaler
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
    spec:
      serviceAccountName: cluster-autoscaler
      containers:
        - image: {{ .Values.image }}
          name: cluster-autoscaler
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
            requests:
              cpu: 100m
              memory: 300Mi
          command:
            - ./cluster-autoscaler
            - --v=4
            - --stderrthreshold=info
            - --logtostderr=true
            - --leader-elect=true
            - --scale-down-delay-after-add=3m
            - --scale-down-delay-after-delete=3m
            - --scale-down-delay-after-failure=3m
            - --scale-down-unneeded-time=3m
            - --cloud-provider=aws
            - --skip-nodes-with-local-storage=false
            - --skip-nodes-with-system-pods=false
            - --expander=most-pods
            - --balance-similar-node-groups
            - --scale-down-utilization-threshold=0.3
            - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/{{ .Values.eksCluster }}
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs/ca-bundle.crt
              readOnly: true
          imagePullPolicy: "Always"
      volumes:
        - name: ssl-certs
          hostPath:
            path: "/etc/ssl/certs/ca-bundle.crt"