---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-external-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes-external-secrets
    chart: kubernetes-external-secrets
  #annotations:
    #eks.amazonaws.com/role-arn: "{{ .Values.iamRole }}"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kubernetes-external-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes-external-secrets
    chart: kubernetes-external-secrets
rules:
  - apiGroups: [""]
    resources: ["secrets", "namespaces"]
    verbs: ["create", "update", "get"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    resourceNames: ["externalsecrets.kubernetes-client.io"]
    verbs: ["get", "update"]
  - apiGroups: ["kubernetes-client.io"]
    resources: ["externalsecrets", "externalsecrets/status"]
    verbs: ["get", "watch", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-external-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubernetes-external-secrets
    chart: kubernetes-external-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-external-secrets
subjects:
  - name: kubernetes-external-secrets
    namespace: {{ .Release.Namespace }}
    kind: ServiceAccount
