apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-autoscaler
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.server }}
  project: shared-services
  source:
    path: helm_charts/node-autoscaler
    repoURL: https://github.com/TechTalkFridays/eks-shared-services.git
    targetRevision: master
    helm:
      valueFiles:
      - helm_vars/engineering/values.yaml
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
