---
iamRole: arn:aws:iam::089522539631:role/kubernetes-external-secrets
image: godaddy/kubernetes-external-secrets:3.1.0
replicas: 1
region: us-east-1
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
