---
iamRole: # Create a iam role which has permission to get/list secrets in AWS secret manager and fill me in
image: godaddy/kubernetes-external-secrets:3.1.0
replicas: 1
region: us-east-1
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
